### PR TITLE
use shout_send_raw and some more errorhandling

### PR DESCRIPTION
**Pull request by daschuer**

### CODE REVIEW

**Comment by daschuer** [comment]
Hi @illuusio, 

I have found a public testing server and I was able to find and fix some pending issue. 
Now broadcasting works reliable. I was able to broadcast with low latency settings and a lot of underflows. I was also able to place a breakpoint and continue after 5s or after 20 s. 
After 20 the buffer is flushed by a disconnect connect cycle.  

So it looks like we have a merge-able version. Please confirm this. 

The state variables are still messed up. Currently we use ~5 variables to store some of the state information. I have tried to move it to a single variable based on your work, but I have messed up the code trying this. So I have reverted all to a working version with the old state variables. 

How would you like to continue with this topic?

**Comment by illuusio** [comment]
Can you determine these state variables so I can take a look a them. Otherwise this look promising.

**Comment by daschuer** [comment]
we have: 
- m_pShout to check if we have a libshout instance
- m_iShoutStatus which carries the last shouterror return values, but it is also tweaked by us and there 
  is an interpretation issue betwean SUCCSESS and CONNECTED, (sometimes Connected is success)
- m_pShoutcastEnabled, is working "halve" an only internal. We may allow to use it from script and keyboard as well. 
- m_pShoutcastNeedUpdateFromPrefs looks quite hacky, but for now I have no better idea. 
- m_pShoutcastNeedUpdateFromPrefs for Skin Feedback, not sure if it works, IMHO this should have three states "Uncconnected" "Connected" "Disconnected(Warning)"
- m_networkStreamWorkerState the new state. 

Maybe we can derive all required states from a rich stated m_networkStreamWorkerState. 
Unfortunately it looks like an other mayor refactoring.  :-/

**Comment by daschuer** [comment]
Now it works like a charm together with the new "ON AIR" indicator in Shade

**Pull request merged**
