### PR TITLE
some improvements with greyed out preferences

### PR DESCRIPTION
**Pull request by daschuer**
Hi @illuusio I have found some time to improve the gray-out response by a signal slot connection

### CODE REVIEW

**Comment by illuusio** [comment]
I don't understand this hint about reconnecting thing.. if there is such I can also implement reconnect.

**Comment by daschuer** [comment]
The other pending reconnection issue, is that: 
There are some error conditions that disconnects from the server. The user has to "fix the issue" and reconnect manually. 
The idea is try to reconnect aromatically if the connection was dropped by any fault. 
This helps to keep broadcasting with an unattended setup.

**Comment by daschuer** [comment]
It happens here: 
https://github.com/daschuer/mixxx/blob/1.12-shoutcast-fixes/src/engine/sidechain/engineshoutcast.cpp#L519
https://github.com/daschuer/mixxx/blob/1.12-shoutcast-fixes/src/engine/sidechain/engineshoutcast.cpp#L450
https://github.com/daschuer/mixxx/blob/1.12-shoutcast-fixes/src/engine/sidechain/engineshoutcast.cpp#L500

**Comment by illuusio** [comment]
I think we should add signals for at least connected and disconnected so it can be automatic handled if reconnection is needed or just checkbox and not disconnect just try to reconnect.

**Comment by daschuer** [comment]
Ah, yes.

**Comment by illuusio** [comment]
I looked code. This doesn't signal shoutcast enginge?

**Comment by daschuer** [comment]
The remaining auto reconnect issue, is unrelated with the previous reconnection on preference changes.
The idea was to reconnect automatically if the connection was dropped because of error conditions. 
IMHO your idea with an signal from the scoutmaster thread will work. We may emit a "Disconnected" signal

**Comment by daschuer** [comment]
We may emit a "Disconnected" signal from the scoutmaster thread, connect it to a slot in the engineshoutcast and reconnect after a reasonable delay until the user stops this by disabling scoutmaster.

**Pull request merged**
